### ISSUE TITLE
Setting simulation parameters

### ISSUE THREAD

**Issue by yonghoonkwon** [XPandora/PhysGaussian#17]
Thank you for sharing valuable research! 
I have a question regarding the configuration parameters for the simulation.

1. How were the parameters defined in the JSON within the config folder determined? Is it necessary to use Houdini SW for this? Where can I refer to learn how to utilize Houdini?

2. When performing simulations on custom data, is it possible to apply characteristics of additional materials not defined (such as jelly, metal, sand, foam, snow, etc.)?

**Comment by Tonychen050400** [comment]
Hi, do you solve that problem? I face the same problem that how to use Houdini
