### ISSUE TITLE
Physical parameters issues

### ISSUE THREAD

**Issue by hongh0** [XPandora/PhysGaussian#2]
Hi,
Thanks for your great work. However, I have some questions about the paper. I would like to understand if the physical parameters of PhysGaussian are provided or estimated from the deformed object in image, like PAC-NeRF.

Thank you.

**Comment by XPandora** [comment]
Hello,

At present, PhysGaussian's material parameters are set manually. However, extending our approach to estimate these parameters from video input is certainly feasible, similar to PAC-NeRF.
