### ISSUE TITLE
Shifting of point cloud to (1,1,1)

### ISSUE THREAD

**Issue by sidsunny** [XPandora/PhysGaussian#21]
Hi! Thank you for sharing your code for the amazing work! I see in the code that the point cloud is shifted to (1,1,1) after normalization. Is there any specific reason for this?

**Comment by XPandora** [comment]
Hello! This is mostly for implementation convenience as our mpm solver requires that all particles are within the first quadrant.

**Comment by sidsunny** [comment]
Okay, thanks! On a similar note, I see that the default parameters in the boundary condition for cuboid are applying Force in the cuboid centered at the point (1,1,0.5) with size (0.5,0.5,0.28) which I believe is in the order (x,y,z). so the bounding box should be x=0.5 to 1.5, y=0.5 to 1.5, z=0.22 to 0.78. So the simulation should happen at the bottom of the plant in the bounding box (yellow) as I show in the figure here. The center of cuboid (1,1,0.5) is shown in pink color.

<img width="558" alt="Screenshot 2024-04-23 at 1 11 13 PM" src="https://github.com/XPandora/PhysGaussian/assets/12964233/da1888ef-3d7f-4e5e-ba04-78c2d56613eb">

<br><br>
However, on running the simulation, the top of the plant is simulated as shown in the below figure:

![output_x](https://github.com/XPandora/PhysGaussian/assets/12964233/d7a1c9d5-16d1-49de-b85e-bb44ff02da52)

<br>
Can you please explain why is this the case?
