### ISSUE TITLE
A question meet when follow the step of python environment settup

### ISSUE THREAD

**Issue by Tonychen050400** [XPandora/PhysGaussian#27]
Hi, Tianyi
I face a problem that when I run the code of "pip install -e gaussian-splatting/submodules/diff-gaussian-rasterization/", it shows below error which means easy_install command is deprecated. Is there any other way to do the same thing as the last two pip install comments in python environment settup area?
![image](https://github.com/XPandora/PhysGaussian/assets/61198124/5ba25caf-2b88-47b2-989e-dd7afbdcbef0)
Best regards,
Haoyu Chen

**Comment by Tonychen050400** [comment]
Solved by installing the visual studio C++ builds tool

**Comment by Inferencer** [comment]
> Solved by installing the visual studio C++ builds tool

before you close this was there any particular year you used to build tools, 2019 or 2022 for example

**Comment by Tonychen050400** [comment]
I download the 2022 build tools to solve this problem

**Comment by XPandora** [comment]
Thank you for sharing your experience, Haoyu. Honestly, I don't have experience setting up the GS environment on Windows. Since it appears this issue has been resolved, I am closing it.
