### ISSUE TITLE
How to use Houdini to check for accurate parameters setting in config file?

### ISSUE THREAD

**Issue by 23wjj** [XPandora/PhysGaussian#29]
Hello, thanks for the fantasy work!
Could you please provide for some guidance on how to set the parameters in the config file via Houdini, such as ```mpm_space_viewpoint_center```，```delta_a```, ```delta_r```, ```delta_e```?
Many thanks!

**Comment by 23wjj** [comment]
the ···mpm_space_viewpoint_center``` refers to the viewpoint center in the mpm space for rendering,  series of ```delta_a````` is used to generate the trajactory of the moving camera.

**Comment by AndreaCastiella** [comment]
Hi, I have one question, how do you choose the value for mpm_space_viewpoint_center? Thanks :)
