### ISSUE TITLE
Need some guidances

### ISSUE THREAD

**Issue by Kedaya66** [XPandora/PhysGaussian#3]
Hello！
I am interested in nerf researches, but I am totally new to this area. So, I wanna ask about the hardware requirements of training nerf models. And could you provide some advice for a beginner to this research area. Thanks!

**Comment by Kedaya66** [comment]
And how long will it cost to train nerf models.

**Comment by XPandora** [comment]
Hi,

You may start by reading the original NeRF paper and some of its popular follow-up work, like Mip-NeRF 360, Instant-NGP, etc. In this work, we use Gaussian Splatting as our 3D representation and typically it takes less than 1 hour to train a scene on a RTX 3090 GPU.

**Comment by Kedaya66** [comment]
Ok！Sincerely thanks for your advice！



发自我的iPhone


------------------ Original ------------------
From: Tianyi Xie ***@***.***&gt;
Date: Thu,Jan 4,2024 5:58 AM
To: XPandora/PhysGaussian ***@***.***&gt;
Cc: Kedaya66 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [XPandora/PhysGaussian] Need some guidances (Issue #3)





 
Hi,
 
You may start by reading the original NeRF paper and some of its popular follow-up work, like Mip-NeRF 360, Instant-NGP, etc. In this work, we use Gaussian Splatting as our 3D representation and typically it takes less than 1 hour to train a scene on a RTX 3090 GPU.
