### ISSUE TITLE
Can you provide config file of pillow to sofa collision in your project page??

### ISSUE THREAD

**Issue by SangHunHan92** [XPandora/PhysGaussian#31]
Hi.
I want to implement cloth simulation via MPM using your code.

For this, I need to handle collision between complex objects, but the provided config file only implements a very simple form of collision (collapsed sand hitting the floor).

I saw a collision between pillow and sofa on the project page. (pillow2sofa.mp4)
Can you provide pillow2sofa json file and pretrained model to reproduces this?

https://github.com/user-attachments/assets/d7011cfc-69b5-4df7-997c-6f2e34e243c2

**Comment by XPandora** [comment]
The config file and pre-trained model have been uploaded.

**Comment by SangHunHan92** [comment]
Thank you very much for your quick updates and thoughtful replies!

**Comment by zhengzzj** [comment]
Could you please tell me where the pre-trained model (pillow2sofa) is? I can't find it.

**Comment by SangHunHan92** [comment]
https://github.com/XPandora/PhysGaussian?tab=readme-ov-file#quick-start

You can download it by clicking "Gaussian Splatting models".

**Comment by zhengzzj** [comment]
Thank you :)
