### ISSUE TITLE
Question about FCR kirchoff stress formulation

### ISSUE THREAD

**Issue by RuihanGao** [XPandora/PhysGaussian#36]
Hi, thanks for the great work!
I have a quick question about the formulation of function `kirchoff_stress_FCR` in `mpm_utils.py`.
I am checking with a [reference](https://www.math.ucla.edu/~cffjiang/research/mpmcourse/mpmcourse.pdf) and it seems that the provided implementation differs from the referece (Eqn 52 in Sec 6.3) by a multiplication of `F^{T}`. Is there any particular reason why it is the case?
Thanks!

**Comment by zeshunzong** [comment]
https://github.com/zeshunzong/warp-mpm/blob/main/mpm_utils.py#L12C5-L12C67

They are two equivalent but different stress representations.

**Comment by RuihanGao** [comment]
Got it, thanks a lot!
