### ISSUE TITLE
code release date

### ISSUE THREAD

**Issue by hengfei-wang** [XPandora/PhysGaussian#5]

**Comment by XPandora** [comment]
We've just returned from a paper submission and are now turning our attention to reorganizing the PhysGaussian code. We aim to make the source code available sometime this month.

**Comment by andypinxinliu** [comment]
> We've just returned from a paper submission and are now turning our attention to reorganizing the PhysGaussian code. We aim to make the source code available sometime this month.

looking forward to see your impressive work

**Comment by tyhuang0428** [comment]
> We've just returned from a paper submission and are now turning our attention to reorganizing the PhysGaussian code. We aim to make the source code available sometime this month.

Congratulations on the acceptance of your paper! When will the code be released?

**Comment by XPandora** [comment]
Thanks for your patience and interest! We've just released the code. More updates are on the way.

**Comment by YingJiang96** [comment]
> Thanks for your patience and interest! We've just released the code. More updates are on the way.

Congratulations!
