### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by JiatengLiu** [XPandora/PhysGaussian#6]
What 's an amazing job! 
And I have a question about the demo of project : have you run a series of demos on a dynamic human? Like driving people to move.

Best wish!!

**Comment by XPandora** [comment]
Thanks for the kind words! 
To accomplish this, you can extract the mesh that will be used for subsequent animation. This allows Gaussian kernels to be embedded into and driven by the mesh. We've demonstrated this approach in one of our recent projects. Feel free to check it out here: https://yingjiang96.github.io/VR-GS/

**Comment by JiatengLiu** [comment]
thanks:)
